version: '3.5'

services:
  workspace:
   volumes:
      - applications-sync:/var/www:nocopy    
  php-fpm:
   volumes:
      - applications-sync:/var/www:nocopy
  nginx:
   volumes:
      - applications-sync:/var/www:nocopy
volumes:
  applications-sync:
    external:
      name: "applications-docker-sync"
